"""存储抽象（tech-stack §7）。

内核（wenyi-core）只依赖 :class:`Storage` 这个 Protocol，不依赖任何具体后端
（不 import RunStore / sqlite3 / psycopg）。由调用方注入实现：

- CLI 本地模式 → :class:`wenyi_core.storage.file.FileStorage`（写 state/ 目录）
- Web 模式     → ``PostgresStorage``（写在 apps/api 中，写 Postgres）

这样 CLI 零基础设施可用，Web 用 Postgres，内核本身不感知存储后端。
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

from ..glossary.store import GlossaryTerm
from ..ingest.models import Chapter, Document

STATUS_PENDING = "pending"
STATUS_DONE = "done"


@runtime_checkable
class Storage(Protocol):
    """翻译内核所需的全部持久化操作的统一接口。

    涵盖原 ``RunStore``（运行态：manifest/章节/上下文/分析/usage/报告/事件）
    与 ``GlossaryStore``（术语库/翻译记忆/冲突）两套职责。
    任何实现（FileStorage / PostgresStorage）都需提供以下全部方法。
    """

    # ── 生命周期 ─────────────────────────────────────────────────────────
    def exists(self) -> bool: ...
    def init_from_document(self, doc: Document) -> dict: ...
    def close(self) -> None: ...

    # ── manifest（书籍元信息 + 各章状态）─────────────────────────────────
    def save_manifest(self, manifest: dict) -> None: ...
    def load_manifest(self) -> dict: ...
    def set_chapter_status(self, ci: int, status: str) -> None: ...
    def pending_chapters(self) -> list[int]: ...

    # ── 章节 / 段落 ──────────────────────────────────────────────────────
    def save_chapter(self, chapter: Chapter) -> None: ...
    def load_chapter(self, ci: int) -> Chapter: ...

    # ── 上下文 / 分析 / usage / 报告 ─────────────────────────────────────
    def save_context(self, data: dict) -> None: ...
    def load_context(self) -> Optional[dict]: ...
    def save_analysis(self, data: dict) -> None: ...
    def load_analysis(self) -> Optional[dict]: ...
    def save_report(self, data: dict) -> None: ...
    def load_report(self) -> Optional[dict]: ...
    def save_usage(self, data: dict) -> None: ...
    def load_usage(self) -> Optional[dict]: ...

    # ── 事件日志（追加式审计 + 行为对账）──────────────────────────────────
    def log_event(self, event: str, **data: Any) -> None: ...
    def list_events(self, *, event_type: Optional[str] = None,
                    limit: int = 200) -> list[dict]: ...

    # ── 术语表 ───────────────────────────────────────────────────────────
    def get_term(self, source: str) -> Optional[GlossaryTerm]: ...
    def upsert_term(self, term: GlossaryTerm,
                    chapter: Optional[int] = None) -> str: ...
    def all_terms(self) -> list[GlossaryTerm]: ...
    def terms_in(self, terms: list[GlossaryTerm],
                 text: str) -> list[GlossaryTerm]: ...
    def terms_in_text(self, text: str) -> list[GlossaryTerm]: ...
    def lock_term(self, source: str, target: Optional[str] = None) -> None: ...
    def delete_term(self, source: str) -> bool: ...
    def mark_conflicts_resolved(self, source: str) -> None: ...
    def open_conflicts(self) -> list[dict]: ...
    def low_confidence_terms(self) -> list[GlossaryTerm]: ...

    # ── 翻译记忆库 ───────────────────────────────────────────────────────
    def add_tm(self, source_text: str, target_text: str,
               chapter: Optional[int] = None) -> None: ...
    def tm_lookup(self, source_text: str) -> Optional[str]: ...

    # ── 统计 ─────────────────────────────────────────────────────────────
    def stats(self) -> dict[str, int]: ...
